from selfdrive.car.isotp_parallel_query import IsoTpParallelQuery
from system.swaglog import cloudlog
import time
import cereal.messaging as messaging

EXT_DIAG_REQUEST = b'\x10\x03'
EXT_DIAG_RESPONSE = b'\x50\x03'

COM_CONT_RESPONSE = b''


def disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x01', timeout=0.1, retry=10, debug=True):
  """Silence an ECU by disabling sending and receiving messages using UDS 0x28.
  The ECU will stay silent as long as openpilot keeps sending Tester Present.

  This is used to disable the radar in some cars. Openpilot will emulate the radar.
  WARNING: THIS DISABLES AEB!"""
  cloudlog.warning(f"ecu disable {hex(addr)} {com_cont_req} ...")
  # sendcan = messaging.pub_sock('sendcan')
  # logcan = messaging.sub_sock('can')
  # time.sleep(1)
  for i in range(retry):
    try:
      query = IsoTpParallelQuery(sendcan, logcan, bus, [addr], [EXT_DIAG_REQUEST], [EXT_DIAG_RESPONSE], -0x280, debug=debug)

      for _, _ in query.get_data(timeout).items():
        cloudlog.warning("communication control disable tx/rx ...")

        query = IsoTpParallelQuery(sendcan, logcan, bus, [addr], [com_cont_req], [COM_CONT_RESPONSE], -0x280, debug=debug)
        query.get_data(0)

        cloudlog.warning("ecu disabled")
        print(f"disabled: {com_cont_req} disabled")
        return True

    except Exception:
      cloudlog.exception("ecu disable exception")

    print(f"ecu disable retry ({i+1}) ...")
  cloudlog.warning("ecu disable failed")
  return False


if __name__ == "__main__":
  sendcan = messaging.pub_sock('sendcan')
  logcan = messaging.sub_sock('can')
  time.sleep(1)

  # honda bosch radar disable
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x00', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x01', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x02', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x04', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x05', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x06', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x07', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x08', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x09', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x10', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x11', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x12', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x13', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x14', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x15', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x16', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x17', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x18', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x19', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x20', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x21', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x22', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x23', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x24', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x25', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x26', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x27', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x28', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x29', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x30', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x31', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x32', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x33', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x34', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x35', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x36', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x37', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x38', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x39', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x40', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x41', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x42', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x43', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x44', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x45', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x46', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x47', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x48', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x49', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x50', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x51', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x52', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x53', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x54', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x55', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x56', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x57', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x58', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x59', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x60', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x61', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x62', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x63', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x64', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x65', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x66', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x67', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x68', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x69', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x70', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x71', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x72', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x73', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x74', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x75', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x76', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x77', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x78', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x79', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x80', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x81', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x82', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x83', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x84', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x85', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x86', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x87', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x88', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x89', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x90', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x91', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x92', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x93', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x94', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x95', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x96', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x97', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x98', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x99', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
