from selfdrive.car.isotp_parallel_query import IsoTpParallelQuery
from system.swaglog import cloudlog

EXT_DIAG_REQUEST = b'\x10\x03'
EXT_DIAG_RESPONSE = b'\x50\x03'

COM_CONT_RESPONSE = b''


def disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x01', timeout=0.1, retry=10, debug=True):
  """Silence an ECU by disabling sending and receiving messages using UDS 0x28.
  The ECU will stay silent as long as openpilot keeps sending Tester Present.

  This is used to disable the radar in some cars. Openpilot will emulate the radar.
  WARNING: THIS DISABLES AEB!"""
  cloudlog.warning(f"ecu disable {hex(addr)} {com_cont_req} ...")
  sendcan = messaging.pub_sock('sendcan')
  logcan = messaging.sub_sock('can')
  time.sleep(1)
  for i in range(retry):
    try:
      query = IsoTpParallelQuery(sendcan, logcan, bus, [addr], [EXT_DIAG_REQUEST], [EXT_DIAG_RESPONSE], -0x280, debug=debug)

      for _, _ in query.get_data(timeout).items():
        cloudlog.warning("communication control disable tx/rx ...")

        query = IsoTpParallelQuery(sendcan, logcan, bus, [addr], [com_cont_req], [COM_CONT_RESPONSE], -0x280, debug=debug)
        query.get_data(0)

        cloudlog.warning("ecu disabled")
        print(f"disabled: {com_cont_req} disabled")
        return True

    except Exception:
      cloudlog.exception("ecu disable exception")

    print(f"ecu disable retry ({i+1}) ...")
  cloudlog.warning("ecu disable failed")
  return False


if __name__ == "__main__":
  import time
  import cereal.messaging as messaging
  sendcan = messaging.pub_sock('sendcan')
  logcan = messaging.sub_sock('can')
  time.sleep(1)

  # honda bosch radar disable
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x00\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x01\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x02\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x03\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x04\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x05\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x06\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x07\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x08\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x09\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x0A\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x0B\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x0C\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x0D\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x0E\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x0F\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x10\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x11\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x12\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x13\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x14\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x15\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x16\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x17\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x18\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x19\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x1A\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x1B\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x1C\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x1D\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x1E\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x1F\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x20\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x21\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x22\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x23\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x24\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x25\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x26\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x27\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x28\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x29\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x2A\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x2B\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x2C\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x2D\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x2E\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x2F\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x30\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x31\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x32\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x33\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x34\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x35\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x36\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x37\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x38\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x39\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x3A\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x3B\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x3C\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x3D\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x3E\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x3F\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x40\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x41\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x42\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x43\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x44\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x45\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x46\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x47\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x48\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x49\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x4A\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x4B\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x4C\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x4D\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x4E\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x4F\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x50\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x51\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x52\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x53\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x54\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x55\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x56\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x57\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x58\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x59\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x5A\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x5B\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x5C\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x5D\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x5E\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x5F\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x60\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x61\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x62\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x63\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x64\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x65\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x66\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x67\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x68\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x69\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x6A\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x6B\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x6C\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x6D\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x6E\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x6F\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x70\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x71\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x72\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x73\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x74\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x75\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x76\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x77\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x78\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x79\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x7A\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x7B\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x7C\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x7D\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x7E\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x7F\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x80\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x81\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x82\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x83\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x84\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x85\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x86\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x87\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x88\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x89\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x8A\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x8B\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x8C\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x8D\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x8E\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x8F\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x90\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x91\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x92\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x93\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x94\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x95\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x96\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x97\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x98\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x99\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x9A\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x9B\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x9C\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x9D\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x9E\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\x9F\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xA0\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xA1\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xA2\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xA3\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xA4\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xA5\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xA6\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xA7\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xA8\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xA9\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xAA\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xAB\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xAC\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xAD\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xAE\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xAF\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xB0\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xB1\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xB2\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xB3\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xB4\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xB5\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xB6\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xB7\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xB8\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xB9\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xBA\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xBB\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xBC\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xBD\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xBE\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xBF\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xC0\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xC1\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xC2\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xC3\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xC4\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xC5\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xC6\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xC7\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xC8\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xC9\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xCA\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xCB\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xCC\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xCD\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xCE\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xCF\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xD0\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xD1\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xD2\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xD3\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xD4\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xD5\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xD6\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xD7\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xD8\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xD9\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xDA\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xDB\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xDC\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xDD\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xDE\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xDF\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xE0\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xE1\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xE2\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xE3\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xE4\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xE5\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xE6\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xE7\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xE8\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xE9\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xEA\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xEB\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xEC\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xED\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xEE\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xEF\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xF0\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xF1\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xF2\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xF3\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xF4\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xF5\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xF6\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xF7\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xF8\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xF9\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xFA\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xFB\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xFC\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xFD\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xFE\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
  disabled = disable_ecu(logcan, sendcan, bus=0, addr=0x753, com_cont_req=b'\x28\xFF\x03', timeout=0.5, debug=False)
  print(f"disabled: {disabled}")
  time.sleep(2)
